### ISSUE TITLE
配置介绍中关于群晖的内容配图是不是放错了？

### ISSUE THREAD

**Issue by leiletter** [SuperNG6/docker-bilbili-helper#1]
aria2的？

**Comment by SuperNG6** [comment]
懒得截图搞新的了，Linux用户权限相关的，通用的，应该能看懂

**Comment by leiletter** [comment]
![image](https://user-images.githubusercontent.com/29282074/99927106-02712c80-2d7f-11eb-846f-5724fb614811.png)
大佬，docker里面映射总是搞不对，请教下
