### ISSUE TITLE
希望可以增加arm32架构 跑在老树莓派 玩客云上

### ISSUE THREAD

**Issue by samondlee** [SuperNG6/docker-bilbili-helper#7]
希望可以增加arm32架构 跑在老树莓派 玩客云上

**Comment by samondlee** [comment]
另外

environment 填写COOKIE 个人觉着 可以修改为 写入shell命令，这样可变性更高一些。。。

参考 jd-script的docker shell

https://github.com/EvineDeng/jd-base/wiki/Docker

**Comment by SuperNG6** [comment]
1、已添加arm32平台版
2、暂不考虑
- 我觉得没有docker-compose方便，修改后up一下就行
- 更改内容过多，已经很稳定了，不想折腾了

**Comment by samondlee** [comment]
玩客云 树莓派docker已测试通过

感谢
